// Generated by GB3D Studio 1.2. Do not edit by hand.
#ifndef GB3D_SCENE_H
#define GB3D_SCENE_H

static const ModelVertex model_vertices[] = {
    {0, -16, 0},
    {0, 16, 0},
    {8, 8, 14},
    {8, -8, 14},
    {16, 8, 0},
    {16, -8, 0},
    {8, 8, -14},
    {8, -8, -14},
    {-8, 8, -14},
    {-8, -8, -14},
    {-16, 8, 0},
    {-16, -8, 0},
    {-8, 8, 14},
    {-8, -8, 14},
};

static const Face3D model_faces[] = {
    {2, 4, 1, 0u},
    {2, 3, 5, 0u},
    {2, 5, 4, 0u},
    {5, 3, 0, 0u},
    {4, 6, 1, 0u},
    {4, 5, 7, 0u},
    {4, 7, 6, 0u},
    {7, 5, 0, 0u},
    {6, 8, 1, 0u},
    {6, 7, 9, 0u},
    {6, 9, 8, 0u},
    {9, 7, 0, 0u},
    {8, 10, 1, 0u},
    {8, 9, 11, 0u},
    {8, 11, 10, 0u},
    {11, 9, 0, 0u},
    {10, 12, 1, 0u},
    {10, 11, 13, 0u},
    {10, 13, 12, 0u},
    {13, 11, 0, 0u},
    {12, 2, 1, 0u},
    {12, 13, 3, 0u},
    {12, 3, 2, 0u},
    {3, 13, 0, 0u},
};

static const Model3D model_model = {
    model_vertices,
    model_faces,
    14u,
    24u,
    -16, 16, -16, 16, -14, 14,
    16u
};

#define SCENE_OBJECT_COUNT 1u
static SceneObject3D scene_objects[(SCENE_OBJECT_COUNT > 0u) ? SCENE_OBJECT_COUNT : 1u] = {
    {&model_model, 0, 0, 0, 0u, 0u, 1u, 1u},
};

#define SCENE_SOLID_COUNT 1u
static const uint8_t scene_solid_indices[(SCENE_SOLID_COUNT > 0u) ? SCENE_SOLID_COUNT : 1u] = {
    0u
};
#define SCENE_SECTOR_CULLING 1u
#define SCENE_SECTOR_SIZE 64
#define SCENE_SECTOR_RADIUS 6
static const int16_t scene_object_sector_x[1] = {
    0
};
static const int16_t scene_object_sector_z[1] = {
    0
};
static const uint8_t scene_object_sector_static[1] = {
    1u
};
#define SCENE_PROFILE_BUILD 0u

#define SCENE_FIXED_CAMERA_FAST 0u
#define SCENE_FIXED_CAMERA_YAW 0u
#define SCENE_FIXED_CAMERA_PITCH -4
#define SCENE_STATIC_WORLD_BAKED_COUNT 0u
static const SceneRenderInfo scene_render_info[(SCENE_OBJECT_COUNT > 0u) ? SCENE_OBJECT_COUNT : 1u] = {
    {0, 0, 0, 0, 0u},
};

#define SCENE_CAMERA_X 0
#define SCENE_CAMERA_Y 0
#define SCENE_CAMERA_Z -64
#define SCENE_CAMERA_YAW 0u
#define SCENE_CAMERA_PITCH 0
#define SCENE_SKY_COLOR 8u
#define SCENE_PLAYER_ENABLED 1u
#define SCENE_PLAYER_X 0
#define SCENE_PLAYER_Y 0
#define SCENE_PLAYER_Z -24
#define SCENE_PLAYER_SPEED 2u
#define SCENE_PLAYER_JUMP_SPEED 7
#define SCENE_PLAYER_GRAVITY 1
#define SCENE_PLAYER_GROUND_Y 0
#define SCENE_PLAYER_HALF_WIDTH 3
#define SCENE_PLAYER_HEIGHT 12
#define SCENE_PLAYER_CAMERA_DISTANCE 48
#define SCENE_PLAYER_CAMERA_HEIGHT 24
#define SCENE_PLAYER_CAMERA_PITCH -4
#define SCENE_PLAYER_COLOR 14u
#define SCENE_PLAYER_VISIBLE 1u
#define SCENE_PLAYER_SPRITE_8X16 1u
#define SCENE_PLAYER_SPRITE_OAM_COUNT 8u
#define SCENE_PLAYER_SPRITE_TILE_COUNT 16u

// 32x32 player image converted to native Game Boy 2bpp sprite tiles.
static const uint8_t scene_player_sprite_tiles[256] = {
    3, 0, 3, 0, 12, 3, 12, 3, 48, 15, 48, 15, 48, 15, 48, 15,
    48, 15, 48, 15, 51, 15, 51, 15, 48, 15, 48, 15, 48, 15, 48, 15,
    192, 0, 192, 0, 48, 192, 48, 192, 12, 240, 12, 240, 3, 252, 3, 252,
    0, 255, 0, 255, 0, 255, 0, 255, 48, 255, 48, 255, 0, 255, 0, 255,
    3, 0, 3, 0, 12, 3, 12, 3, 48, 15, 48, 15, 192, 63, 192, 63,
    0, 255, 0, 255, 0, 255, 0, 255, 12, 255, 12, 255, 0, 255, 0, 255,
    192, 0, 192, 0, 48, 192, 48, 192, 12, 240, 12, 240, 12, 240, 12, 240,
    12, 240, 12, 240, 204, 240, 204, 240, 12, 240, 12, 240, 12, 240, 12, 240,
    12, 3, 12, 3, 3, 0, 3, 0, 3, 0, 3, 0, 0, 0, 0, 0,
    3, 0, 3, 0, 12, 3, 12, 3, 15, 0, 15, 0, 0, 0, 0, 0,
    15, 255, 15, 255, 0, 255, 0, 255, 192, 63, 192, 63, 192, 63, 192, 63,
    0, 255, 0, 255, 48, 192, 48, 192, 0, 0, 0, 0, 0, 0, 0, 0,
    240, 255, 240, 255, 3, 252, 3, 252, 15, 240, 15, 240, 12, 240, 12, 240,
    3, 252, 3, 252, 12, 3, 12, 3, 15, 0, 15, 0, 0, 0, 0, 0,
    48, 192, 48, 192, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 48, 192, 48, 192, 0, 0, 0, 0, 0, 0, 0, 0,
};
static const palette_color_t scene_player_sprite_palette[4] = {
    RGB(0, 0, 0),
    RGB(8, 6, 3),
    RGB(19, 14, 8),
    RGB(29, 24, 16),
};

// ---- V7 NPC hardware-sprite data ----
#define SCENE_NPC_COUNT 1u
#define SCENE_SPRITE_8X16 1u
#define SCENE_NPC_SPRITE_OAM_COUNT 8u
#define SCENE_NPC_SPRITE_TILE_COUNT 16u
static const int16_t scene_npc_start_x[1] = {
    18,
};
static const int16_t scene_npc_start_y[1] = {
    0,
};
static const int16_t scene_npc_start_z[1] = {
    18,
};
static const uint8_t scene_npc_height[1] = {
    12u,
};
static const uint8_t scene_npc_visible[1] = {
    1u,
};
static const uint8_t scene_npc_sprite_tiles[1][256] = {
    {
        3, 0, 3, 0, 12, 3, 12, 3, 48, 15, 48, 15, 48, 15, 48, 15,
        48, 15, 48, 15, 51, 15, 51, 15, 48, 15, 48, 15, 48, 15, 48, 15,
        192, 0, 192, 0, 48, 192, 48, 192, 12, 240, 12, 240, 3, 252, 3, 252,
        0, 255, 0, 255, 0, 255, 0, 255, 48, 255, 48, 255, 0, 255, 0, 255,
        3, 0, 3, 0, 12, 3, 12, 3, 48, 15, 48, 15, 192, 63, 192, 63,
        0, 255, 0, 255, 0, 255, 0, 255, 12, 255, 12, 255, 0, 255, 0, 255,
        192, 0, 192, 0, 48, 192, 48, 192, 12, 240, 12, 240, 12, 240, 12, 240,
        12, 240, 12, 240, 204, 240, 204, 240, 12, 240, 12, 240, 12, 240, 12, 240,
        12, 3, 12, 3, 3, 0, 3, 0, 3, 0, 3, 0, 0, 0, 0, 0,
        3, 0, 3, 0, 12, 3, 12, 3, 15, 0, 15, 0, 0, 0, 0, 0,
        15, 255, 15, 255, 0, 255, 0, 255, 192, 63, 192, 63, 192, 63, 192, 63,
        0, 255, 0, 255, 48, 192, 48, 192, 0, 0, 0, 0, 0, 0, 0, 0,
        240, 255, 240, 255, 3, 252, 3, 252, 15, 240, 15, 240, 12, 240, 12, 240,
        3, 252, 3, 252, 12, 3, 12, 3, 15, 0, 15, 0, 0, 0, 0, 0,
        48, 192, 48, 192, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 48, 192, 48, 192, 0, 0, 0, 0, 0, 0, 0, 0,
    },
};
static const palette_color_t scene_npc_sprite_palettes[1][4] = {
    {RGB(0, 0, 0), RGB(8, 6, 3), RGB(19, 14, 8), RGB(29, 24, 16)},
};

// ---- Studio 1.2 hardware Window HUD / UI ----
#define SCENE_UI_COUNT 2u
#define SCENE_WINDOW_ENABLED 1u
#define SCENE_WINDOW_X 0u
#define SCENE_WINDOW_Y 112u
#define SCENE_WINDOW_BG_COLOR 0u
static const char scene_ui_text_0[] = "SCORE";
static GB3DUIElement scene_ui[(SCENE_UI_COUNT > 0u) ? SCENE_UI_COUNT : 1u] = {
    {0u, 0u, 0u, 0u, 10u, 3u, 1u, 1u, 0, 10, scene_ui_text_0},
    {1u, 0u, 2u, 5u, 4u, 3u, 1u, 0u, 8, 10, 0},
};

// Export-time compiled GB3D scripts. No parser/VM runs on the Game Boy.
static int16_t gbv_object_0_turn_timer = 0;
static int16_t gbv_npc_0_timer = 0;
static int16_t gbv_npc_0_direction = 0;

static void scene_script_start(void) {
    gbv_object_0_turn_timer = (int16_t)(0);
    gbv_npc_0_timer = (int16_t)(0);
    gbv_npc_0_direction = (int16_t)(1);
}

static void scene_script_update(void) {
    gbv_object_0_turn_timer += (int16_t)(1);
    if (((gbv_object_0_turn_timer >= 2))) {
        scene_objects[0].rot_x = (uint8_t)(scene_objects[0].rot_x + (0));
        scene_objects[0].rot_y = (uint8_t)(scene_objects[0].rot_y + (1));
        gbv_object_0_turn_timer = (int16_t)(0);
    }
    npcs[0].x += gbv_npc_0_direction;
    npcs[0].y += 0;
    npcs[0].z += 0;
    gbv_npc_0_timer += (int16_t)(1);
    if (((gbv_npc_0_timer >= 20))) {
        gbv_npc_0_direction *= (int16_t)((-1));
        gbv_npc_0_timer = (int16_t)(0);
    }
}

static void scene_script_a(void) {
    gb3d_ui_add_value(0u, (int16_t)(5));
}

static void scene_script_b(void) {
    gb3d_ui_add_value(0u, (int16_t)(1));
}

static void scene_script_select(void) {
    /* empty */
}

static void scene_script_start_button(void) {
    /* empty */
}

static void scene_script_up(void) {
    /* empty */
}

static void scene_script_down(void) {
    /* empty */
}

static void scene_script_left(void) {
    /* empty */
}

static void scene_script_right(void) {
    /* empty */
}

static void scene_script_a_held(void) {
    /* empty */
}

static void scene_script_b_held(void) {
    /* empty */
}

static void scene_script_select_held(void) {
    /* empty */
}

static void scene_script_up_held(void) {
    /* empty */
}

static void scene_script_down_held(void) {
    /* empty */
}

static void scene_script_left_held(void) {
    /* empty */
}

static void scene_script_right_held(void) {
    /* empty */
}

#endif
